#!/bin/bash
# Script to update README.md with the current output from `make help`
#
# This script replaces the hardcoded Makefile help output in README.md
# with the actual output generated by running `make help`.

set -euo pipefail

# Navigate to repository root
cd "$(dirname "$0")/../.."

README_FILE="README.md"
TEMP_FILE=$(mktemp)

# Generate the help output from Makefile and strip ANSI color codes and make[1] messages
HELP_OUTPUT=$(make help 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' | grep -v "^make\[" | grep -v "Entering directory" | grep -v "Leaving directory")

# Create the new README with updated help output
awk -v help_output="$HELP_OUTPUT" '
BEGIN {
    in_help_block = 0
    help_printed = 0
}

# Detect start of help output block
/^Run `make help` to see all available targets:$/ {
    print
    getline
    if ($0 == "") {
        print
    }
    getline
    if ($0 ~ /^```makefile$/) {
        print "```makefile"
        print help_output
        in_help_block = 1
        help_printed = 1
        next
    }
}

# Skip lines inside the old help block
in_help_block == 1 && /^```$/ {
    print "```"
    in_help_block = 0
    next
}

in_help_block == 1 {
    next
}

# Print all other lines
{
    print
}
' "$README_FILE" > "$TEMP_FILE"

# Replace the original README with the updated version
mv "$TEMP_FILE" "$README_FILE"

echo "README.md updated with current 'make help' output"
