# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
name: 'Sync Config Templates'
description: 'Sync configuration templates into a project and create a pull request if needed'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync config files from .config-templates'
    required: false
  #include:
  #  description: 'List of files and folders to include'
  #  default: |
  #    CODE_OF_CONDUCT.md
  #    CONTRIBUTING.md
  #    ruff.toml
  #    Makefile
  #    .pre-commit-config.yaml
  #    .editorconfig
  #    .gitignore
  #    .github
  #  required: false
  exclude:
    description: 'List of files to exclude'
    default: |
      .git
      README.md
      LICENSE
      action.yml
      .github/workflows/sync.yml

  #  default: 'LICENSE'
  #  required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Git repository
      run: |
        git rev-parse --is-inside-work-tree > /dev/null || {
          echo "❌ Not in a git repository"
          exit 1
        }
      shell: bash

    - name: Download and apply templates
      run: |
        set -euo pipefail

        REPO_URL="https://github.com/tschm/.config-templates"
        TEMP_DIR="$(mktemp -d)"
        FILTERED_DIR="$(mktemp -d)"
        trap 'rm -rf "$TEMP_DIR" "$FILTERED_DIR"' EXIT

        echo "📥 Downloading template archive..."
        curl -sSL -o templates.zip "$REPO_URL/archive/refs/heads/main.zip"

        echo "📦 Extracting..."
        unzip -q templates.zip -d "$TEMP_DIR"
        rm -f templates.zip

        EXTRACTED_DIR="${TEMP_DIR}/.config-templates-main"
        ls -all ${EXTRACTED_DIR}

        # Remove excluded items
        while IFS= read -r item; do
          item="$(echo "$item" | xargs)"
          [ -n "$item" ] && rm -rf "$EXTRACTED_DIR/$item"
        done <<< "${{ inputs.exclude }}"

        echo "📂 Copying to working directory..."
        cp -Rf "${EXTRACTED_DIR}/." .

        ls -all .

        echo "✅ Sync complete. Changed files:"
        git status --short || true
      shell: bash
