# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
name: 'Sync Config Templates'
description: 'Sync configuration templates into a project and create a pull request if needed'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to in the target repo'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync config files from .config-templates'
    required: false
  include:
    description: 'List of files and folders to include (multi-line)'
    default: |
      CODE_OF_CONDUCT.md
      CONTRIBUTING.md
      Makefile
      .pre-commit-config.yaml
      .editorconfig
      .gitignore
      .github
      .devcontainer
      taskfiles
      Taskfile.yml
    required: false
  exclude:
    description: 'List of files and folders to exclude (multi-line)'
    default: |
      .git
      README.md
      LICENSE
      action.yml
      .github/workflows/sync.yml
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Git repository
      run: |
        git rev-parse --is-inside-work-tree > /dev/null || {
          echo "❌ Not in a git repository"
          exit 1
        }
      shell: bash

    - name: Sparse checkout from template repo
      uses: actions/checkout@v5
      with:
        repository: 'tschm/.config-templates'
        path: .template-temp
        ref: main
        sparse-checkout: ${{ inputs.include }}
        sparse-checkout-cone-mode: false
        fetch-depth: 0

    - name: Apply excludes
      if: ${{ inputs.exclude != '' }}
      shell: bash
      run: |
        echo "🔍 Processing exclude list..."
        while IFS= read -r item; do
          item="$(echo "$item" | xargs)"
          [ -z "$item" ] && continue
          echo "  Excluding: $item"
          rm -rf ".template-temp/$item"
        done <<< "${{ inputs.exclude }}"

    - name: Copy template files into target repo
      shell: bash
      run: |
        echo "📂 Copying template files into repo..."
        cp -R .template-temp/. .

    - name: Show final synced files
      shell: bash
      run: |
        echo "📂 Final synced files:"
        ls -R .

    - name: Commit and push changes
      shell: bash
      run: |
        git checkout -B "${{ inputs.branch }}"
        git add -A
        if git diff --cached --quiet; then
          echo "✅ No changes to commit"
          exit 0
        fi
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "${{ inputs.commit-message }}"
        git push origin "${{ inputs.branch }}" --force
