# This Dockerfile.dockerignore file is located in the docker/ folder for better organization.
# A symlink at the repository root (Dockerfile.dockerignore -> docker/Dockerfile.dockerignore) allows
# Docker to find it when building with the root directory as the build context.
# See: https://stackoverflow.com/questions/28097064/dockerignore-ignore-everything-except-a-file-and-the-dockerfile

# Ignore Everything
**

!pyproject.toml
!uv.lock
!README.md
!src/

**/__pycache__
**/*.pyc
