# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Action: Setup Project (composite action)
#
# Purpose: Bootstrap a Python project in GitHub Actions by:
#   - Installing Task, uv, and uvx into a local ./bin directory
#   - Optionally rendering the repository from a Copier template for tests
#   - Detecting presence of pyproject.toml and exposing it as an output
#   - Creating a virtual environment with uv and syncing dependencies
#
# Inputs:
#   - python-version: Python version used for the virtual environment (default: 3.12)
#
# Outputs:
#   - pyproject_exists: "true" if pyproject.toml exists, otherwise "false"
#
# Notes:
#   - Safe to run in repositories without pyproject.toml; dependency sync will be skipped.
#   - Used by workflows such as CI, Book, Marimo, and Release.

name: 'Setup Project'
description: 'Setup the project'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

outputs:
  pyproject_exists:
    description: 'Flag indicating whether pyproject.toml exists'
    value: ${{ steps.check_pyproject.outputs.exists }}

runs:
  using: 'composite'
  steps:
    # Use actions/setup-python before using uv, to ensure the version exists
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Task
      uses: go-task/setup-task@v1

    - name: Install uv/uvx
      uses: astral-sh/setup-uv@v7

    - name: Set up task, uv, uvx and the venv
      shell: bash
      run: |
        set -euo pipefail

        #mkdir -p bin

        # Add ./bin to the PATH for subsequent steps (note: not current shell)
        #echo "Adding ./bin to PATH"
        #echo "$(pwd)/bin" >> "$GITHUB_PATH"
        #echo $GITHUB_PATH

        # Install Task (idempotent)
        #if [ -x "./bin/task" ]; then
        #  echo "task already present in ./bin, skipping installation"
        #else
        #  echo "Installing go-task (Taskfile) into ./bin"
        #  curl -fsSL https://taskfile.dev/install.sh | sh -s -- -d -b ./bin
        #fi

        # Install uv (idempotent)
        #if [ -x "./bin/uv" ]; then
        #  echo "uv already present in ./bin, skipping installation"
        #else
        #  echo "Installing uv into ./bin"
        #  curl -fsSL https://astral.sh/uv/install.sh | UV_INSTALL_DIR="./bin" sh
        #fi

        # Verify installations (use explicit paths because PATH change doesn't affect current shell)
        task --version
        uv --version
        uvx --version

        ls -all

    - name: Render the project
      if: hashFiles('tests/resources/render.yml') != ''
      shell: bash
      run: |
        pip install copier

        # Render the current folder in-place
        copier copy . . \
          --data-file ./tests/resources/render.yml \
          --force \
          --overwrite \
          --quiet

        # Delete all remaining .jinja files
        find . -type f -name "*.jinja" -exec rm -f {} +

        # Delete all folders that still contain {{ ... }}
        find . -depth -type d -name "*{{*}}*" -exec rm -rf {} +

        ls -R

    - name: Check for pyproject.toml
      id: check_pyproject
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Build the virtual environment
      shell: bash
      run: uv venv --python ${{ inputs.python-version }}

    - name: "Install the dependencies for ${{ github.repository }} if pyproject.toml exists"
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          uv sync --all-extras
        else
          echo "No pyproject.toml found, skipping package installation"
        fi
