# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Workflow: Sync
# Purpose: This workflow synchronizes configuration files from the template repository
#          to other repositories, creating a pull request with the changes.
#
# Trigger: This workflow runs manually via workflow_dispatch
#
# Components:
#   - 📥 Checkout the target repository
#   - 🔄 Sync configuration templates
#   - 📝 Create a pull request with the changes

#name: SYNC

#on:
#  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * 1'  # Weekly on Monday at midnight

#permissions:
#  contents: write  # Needed to create releases

name: Sync Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight

#permissions:
#  contents: write   

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
