# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
name: 'Sync Config Templates'
description: 'Sync configuration templates into a project and create a pull request if needed'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync config files from .config-templates'
    required: false
  include:
    description: 'Comma-separated list of files and folders to include (empty = include all)'
    default: 'CODE_OF_CONDUCT.md,CONTRIBUTING.md,ruff.toml,Makefile,.pre-commit-config.yaml,.editorconfig,taskfiles,.gitignore'
    required: false
  exclude:
    description: 'Comma-separated list of files and folders to exclude'
    default: 'LICENSE,.github/workflows/sync.yml'
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Git repository
      run: |
        git rev-parse --is-inside-work-tree > /dev/null || {
          echo "❌ Not in a git repository"
          exit 1
        }
      shell: bash

    - name: Download and apply templates
      run: |
        set -euo pipefail

        REPO_URL="https://github.com/tschm/.config-templates"
        TEMP_DIR="$(mktemp -d)"
        FILTERED_DIR="$(mktemp -d)"
        trap 'rm -rf "$TEMP_DIR" "$FILTERED_DIR"' EXIT

        echo "📥 Downloading template archive..."
        curl -sSL -o templates.zip "$REPO_URL/archive/refs/heads/main.zip"

        echo "📦 Extracting..."
        unzip -q templates.zip -d "$TEMP_DIR"
        rm -f templates.zip

        EXTRACTED_DIR="${TEMP_DIR}/.config-templates-main"

        # Parse includes
        INCLUDES=()
        if [ -n "${{ inputs.include }}" ]; then
          IFS=',' read -ra INCLUDES <<< "${{ inputs.include }}"
          # trim whitespace
          INCLUDES=($(printf "%s\n" "${INCLUDES[@]}" | xargs))
        fi

        # Parse excludes
        EXCLUDES=()
        if [ -n "${{ inputs.exclude }}" ]; then
          IFS=',' read -ra EXCLUDES <<< "${{ inputs.exclude }}"
          # trim whitespace
          EXCLUDES=($(printf "%s\n" "${EXCLUDES[@]}" | xargs))
        fi

        echo "🔍 Processing template files..."
        COPY_SOURCE="$FILTERED_DIR"

        # Copy only included items (minus excludes)
        for item in "${INCLUDES[@]}"; do
          if [ -e "${EXTRACTED_DIR}/$item" ]; then
            echo "  Including: $item"
            if [ -d "${EXTRACTED_DIR}/$item" ]; then
              mkdir -p "${FILTERED_DIR}/$(dirname "$item")"
              cp -R "${EXTRACTED_DIR}/$item" "${FILTERED_DIR}/$(dirname "$item")/"
            else
              mkdir -p "${FILTERED_DIR}/$(dirname "$item")"
              cp "${EXTRACTED_DIR}/$item" "${FILTERED_DIR}/$item"
            fi
          else
            echo "  ⚠️ Warning: Include item '$item' not found in template"
          fi
        done

        for ex in "${EXCLUDES[@]}"; do
          if [ -e "$FILTERED_DIR/$ex" ]; then
            echo "  Removing excluded: $ex"
            rm -rf "$FILTERED_DIR/$ex"
          fi
        done

        echo "📂 Copying to working directory..."
        cp -Rf "${FILTERED_DIR}/." .

        echo "✅ Sync complete. Changed files:"
        git status --short || true
      shell: bash
